/**
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.formatting2;

import at.jku.bise.shipyardV4.services.ShipyardV4GrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import shipyardV4.Shipyard;
import shipyardV4.ShipyardPropertiesAbstract;
import shipyardV4.ShipyardV4Root;

@SuppressWarnings("all")
public class ShipyardV4Formatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ShipyardV4GrammarAccess _shipyardV4GrammarAccess;
  
  protected void _format(final ShipyardV4Root shipyardV4Root, @Extension final IFormattableDocument document) {
    document.<Shipyard>format(shipyardV4Root.getShipyardV4Root());
  }
  
  protected void _format(final Shipyard shipyard, @Extension final IFormattableDocument document) {
    EList<ShipyardPropertiesAbstract> _shipyard = shipyard.getShipyard();
    for (final ShipyardPropertiesAbstract shipyardPropertiesAbstract : _shipyard) {
      document.<ShipyardPropertiesAbstract>format(shipyardPropertiesAbstract);
    }
  }
  
  public void format(final Object shipyard, final IFormattableDocument document) {
    if (shipyard instanceof XtextResource) {
      _format((XtextResource)shipyard, document);
      return;
    } else if (shipyard instanceof Shipyard) {
      _format((Shipyard)shipyard, document);
      return;
    } else if (shipyard instanceof ShipyardV4Root) {
      _format((ShipyardV4Root)shipyard, document);
      return;
    } else if (shipyard instanceof EObject) {
      _format((EObject)shipyard, document);
      return;
    } else if (shipyard == null) {
      _format((Void)null, document);
      return;
    } else if (shipyard != null) {
      _format(shipyard, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(shipyard, document).toString());
    }
  }
}
