/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ShipyardV4ProposalProvider extends AbstractShipyardV4ProposalProvider {
}
