/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ShipyardV4UiModule extends AbstractShipyardV4UiModule {

	public ShipyardV4UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
