/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.ide;

import at.jku.bise.shipyardV4.ShipyardV4RuntimeModule;
import at.jku.bise.shipyardV4.ShipyardV4StandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ShipyardV4IdeSetup extends ShipyardV4StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ShipyardV4RuntimeModule(), new ShipyardV4IdeModule()));
	}
	
}
