/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.ide;


/**
 * Use this class to register ide components.
 */
public class ShipyardV4IdeModule extends AbstractShipyardV4IdeModule {
}
