/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ShipyardV4StandaloneSetup extends ShipyardV4StandaloneSetupGenerated {

	public static void doSetup() {
		new ShipyardV4StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
