/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ShipyardV4RuntimeModule extends AbstractShipyardV4RuntimeModule {
}
