/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ShipyardV4ScopeProvider extends AbstractShipyardV4ScopeProvider {

}
