/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.ui;

import at.jku.bise.shipyardV4.ui.internal.ShipyardV4Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ShipyardV4ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ShipyardV4Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ShipyardV4Activator activator = ShipyardV4Activator.getInstance();
		return activator != null ? activator.getInjector(ShipyardV4Activator.AT_JKU_BISE_SHIPYARDV4_SHIPYARDV4) : null;
	}

}
