/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.parser.antlr;

import at.jku.bise.shipyardV4.parser.antlr.internal.InternalShipyardV4Parser;
import at.jku.bise.shipyardV4.services.ShipyardV4GrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ShipyardV4Parser extends AbstractAntlrParser {

	@Inject
	private ShipyardV4GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalShipyardV4Parser createParser(XtextTokenStream stream) {
		return new InternalShipyardV4Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ShipyardV4Root";
	}

	public ShipyardV4GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ShipyardV4GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
