/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ShipyardV4AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/jku/bise/shipyardV4/parser/antlr/internal/InternalShipyardV4.tokens");
	}
}
