/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.ui.tests;

import at.jku.bise.shipyardV4.ui.internal.ShipyardV4Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ShipyardV4UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ShipyardV4Activator.getInstance().getInjector("at.jku.bise.shipyardV4.ShipyardV4");
	}

}
