/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractShipyardV4ScopeProvider extends DelegatingScopeProvider {
}
