/*
 * generated by Xtext 2.25.0
 */
package at.jku.bise.shipyardV4.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractShipyardV4Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://jku.bise.at/shipyardV4"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://at.jku.bise/jsonMetaschemaMM"));
		return result;
	}
}
